In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Electric_Vehicle_Population_Data.csv to Electric_Vehicle_Population_Data.csv

In [ ]:
import pandas as pd

df = pd.read_csv("Electric_Vehicle_Population_Data.csv")

print("Rows and columns:", df.shape)

df.head()

Rows and columns: (135038, 17)

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,5YJ3E1EA0K,Thurston,Tumwater,WA,98512.0,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220.0,0.0,22.0,242565116,POINT (-122.91310169999997 47.01359260000004),PUGET SOUND ENERGY INC,5.306701e+10
1,1N4BZ1DV4N,Island,Clinton,WA,98236.0,2022,NISSAN,LEAF,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,10.0,183272785,POINT (-122.35936399999997 47.97965520000008),PUGET SOUND ENERGY INC,5.302997e+10
2,5YJ3E1EA0L,Snohomish,Snohomish,WA,98290.0,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,266.0,0.0,44.0,112552366,POINT (-122.09150499999998 47.91555500000004),PUGET SOUND ENERGY INC,5.306105e+10
3,5YJ3E1EBXL,King,Seattle,WA,98134.0,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,322.0,0.0,11.0,6336319,POINT (-122.32981499999994 47.579810000000066),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
4,5YJSA1CP0D,Snohomish,Edmonds,WA,98020.0,2013,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,208.0,69900.0,21.0,186212960,POINT (-122.37507 47.80807000000004),PUGET SOUND ENERGY INC,5.306105e+10

In [ ]:
# Step 2: Inspect the dataset

print("Dataset shape:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

Dataset shape: (135038, 17)

Column names:
['VIN (1-10)', 'County', 'City', 'State', 'Postal Code', 'Model Year', 'Make', 'Model', 'Electric Vehicle Type', 'Clean Alternative Fuel Vehicle (CAFV) Eligibility', 'Electric Range', 'Base MSRP', 'Legislative District', 'DOL Vehicle ID', 'Vehicle Location', 'Electric Utility', '2020 Census Tract']

Data types:
VIN (1-10)                                            object
County                                                object
City                                                  object
State                                                 object
Postal Code                                          float64
Model Year                                             int64
Make                                                  object
Model                                                 object
Electric Vehicle Type                                 object
Clean Alternative Fuel Vehicle (CAFV) Eligibility     object
Electric Range                                       float64
Base MSRP                                            float64
Legislative District                                 float64
DOL Vehicle ID                                         int64
Vehicle Location                                      object
Electric Utility                                      object
2020 Census Tract                                    float64
dtype: object

Missing values:
VIN (1-10)                                             0
County                                                 8
City                                                   8
State                                                  0
Postal Code                                            8
Model Year                                             0
Make                                                   0
Model                                                249
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                         1
Base MSRP                                              1
Legislative District                                 312
DOL Vehicle ID                                         0
Vehicle Location                                      10
Electric Utility                                       8
2020 Census Tract                                      8
dtype: int64

In [ ]:
# Step 3: Check for duplicate rows

print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [ ]:
# Step 4: Clean important text columns

text_columns = [
    "County",
    "City",
    "State",
    "Make",
    "Model",
    "Electric Vehicle Type",
    "Clean Alternative Fuel Vehicle (CAFV) Eligibility",
    "Electric Utility"
]

# Remove extra spaces
for col in text_columns:
    df[col] = df[col].astype("string").str.strip()

# Standardize Make and Model
df["Make"] = df["Make"].str.upper()
df["Model"] = df["Model"].str.upper()

# Fill missing Make/Model
df["Make"] = df["Make"].fillna("UNKNOWN")
df["Model"] = df["Model"].fillna("UNKNOWN")

print("Text cleaning completed.")

Text cleaning completed.

In [ ]:
# Step 5: Create simplified EV Type and CAFV Status

df["EV Type"] = df["Electric Vehicle Type"].map({
    "Battery Electric Vehicle (BEV)": "BEV",
    "Plug-in Hybrid Electric Vehicle (PHEV)": "PHEV"
})

df["EV Type"] = df["EV Type"].fillna("Unknown")


df["CAFV Status"] = df[
    "Clean Alternative Fuel Vehicle (CAFV) Eligibility"
].map({
    "Clean Alternative Fuel Vehicle Eligible": "Eligible",
    "Eligibility unknown as battery range has not been researched": "Unknown",
    "Not eligible due to low battery range": "Not Eligible"
})

df["CAFV Status"] = df["CAFV Status"].fillna("Unknown")


print("EV Type values:")
print(df["EV Type"].value_counts())

print("\nCAFV Status values:")
print(df["CAFV Status"].value_counts())

EV Type values:
EV Type
BEV     103882
PHEV     31156
Name: count, dtype: int64

CAFV Status values:
CAFV Status
Eligible        61221
Unknown         56983
Not Eligible    16834
Name: count, dtype: int64

In [ ]:
# Step 6: Clean Electric Range

import numpy as np

# Convert to numeric
df["Electric Range"] = pd.to_numeric(
    df["Electric Range"],
    errors="coerce"
)

# Replace 0 with missing value
df["Electric Range Clean"] = df["Electric Range"].replace(0, np.nan)

print("Original Electric Range:")
print(df["Electric Range"].describe())

print("\nClean Electric Range:")
print(df["Electric Range Clean"].describe())

print("\nMissing values after cleaning:",
      df["Electric Range Clean"].isna().sum())

Original Electric Range:
count    135037.000000
mean         74.591964
std          98.744120
min           0.000000
25%           0.000000
50%          21.000000
75%         150.000000
max         337.000000
Name: Electric Range, dtype: float64

Clean Electric Range:
count    78054.000000
mean       129.047518
std         99.203267
min          6.000000
25%         32.000000
50%         84.000000
75%        215.000000
max        337.000000
Name: Electric Range Clean, dtype: float64

Missing values after cleaning: 56984

In [ ]:
# Step 7: Clean Base MSRP

df["Base MSRP"] = pd.to_numeric(
    df["Base MSRP"],
    errors="coerce"
)

# Replace 0 with missing value
df["MSRP Clean"] = df["Base MSRP"].replace(0, np.nan)

print("Original MSRP:")
print(df["Base MSRP"].describe())

print("\nClean MSRP:")
print(df["MSRP Clean"].describe())

print("\nMissing values after cleaning:",
      df["MSRP Clean"].isna().sum())

Original MSRP:
count    135037.000000
mean       1448.407325
std        9683.658138
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max      845000.000000
Name: Base MSRP, dtype: float64

Clean MSRP:
count      3425.000000
mean      57106.154745
std       22779.563622
min       31950.000000
25%       39995.000000
50%       59900.000000
75%       69900.000000
max      845000.000000
Name: MSRP Clean, dtype: float64

Missing values after cleaning: 131613

In [ ]:
# Step 8: Create analytical columns

# Vehicle age
current_year = 2026

df["Vehicle Age"] = current_year - df["Model Year"]

# Remove unrealistic future model years
df.loc[df["Vehicle Age"] < 0, "Vehicle Age"] = np.nan


# Range category
df["Range Category"] = pd.cut(
    df["Electric Range Clean"],
    bins=[-1, 100, 200, 300, np.inf],
    labels=[
        "Low Range",
        "Medium Range",
        "High Range",
        "Very High Range"
    ]
)


# Check results
print("Vehicle Age:")
print(df["Vehicle Age"].describe())

print("\nRange Category:")
print(df["Range Category"].value_counts(dropna=False))

Vehicle Age:
count    135038.000000
mean          6.337120
std           3.001676
min           2.000000
25%           4.000000
50%           5.000000
75%           8.000000
max          29.000000
Name: Vehicle Age, dtype: float64

Range Category:
Range Category
NaN                56984
Low Range          41093
High Range         27782
Medium Range        6558
Very High Range     2621
Name: count, dtype: int64

In [ ]:
# Step 9: Save the cleaned dataset

output_file = "EV_Population_Cleaned.csv"

df.to_csv(output_file, index=False)

print("Cleaned dataset saved successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("File:", output_file)

Cleaned dataset saved successfully!
Rows: 135038
Columns: 23
File: EV_Population_Cleaned.csv

In [ ]:
# Download cleaned dataset

from google.colab import files

files.download("EV_Population_Cleaned.csv")

In [ ]:
# Step 10: Final verification

print("Final dataset shape:", df.shape)

print("\nNew columns created:")
print([
    "EV Type",
    "CAFV Status",
    "Electric Range Clean",
    "MSRP Clean",
    "Vehicle Age",
    "Range Category"
])

print("\nFirst 5 rows:")
display(df.head())

Final dataset shape: (135038, 23)

New columns created:
['EV Type', 'CAFV Status', 'Electric Range Clean', 'MSRP Clean', 'Vehicle Age', 'Range Category']

First 5 rows:

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,...,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract,EV Type,CAFV Status,Electric Range Clean,MSRP Clean,Vehicle Age,Range Category
0,5YJ3E1EA0K,Thurston,Tumwater,WA,98512.0,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,...,242565116,POINT (-122.91310169999997 47.01359260000004),PUGET SOUND ENERGY INC,5.306701e+10,BEV,Eligible,220.0,NaN,7.0,High Range
1,1N4BZ1DV4N,Island,Clinton,WA,98236.0,2022,NISSAN,LEAF,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,...,183272785,POINT (-122.35936399999997 47.97965520000008),PUGET SOUND ENERGY INC,5.302997e+10,BEV,Unknown,NaN,NaN,4.0,NaN
2,5YJ3E1EA0L,Snohomish,Snohomish,WA,98290.0,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,...,112552366,POINT (-122.09150499999998 47.91555500000004),PUGET SOUND ENERGY INC,5.306105e+10,BEV,Eligible,266.0,NaN,6.0,High Range
3,5YJ3E1EBXL,King,Seattle,WA,98134.0,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,...,6336319,POINT (-122.32981499999994 47.579810000000066),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10,BEV,Eligible,322.0,NaN,6.0,Very High Range
4,5YJSA1CP0D,Snohomish,Edmonds,WA,98020.0,2013,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,...,186212960,POINT (-122.37507 47.80807000000004),PUGET SOUND ENERGY INC,5.306105e+10,BEV,Eligible,208.0,69900.0,13.0,High Range

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving EV_Population_Cleaned.csv to EV_Population_Cleaned.csv

In [ ]:
import pandas as pd

df = pd.read_csv("EV_Population_Cleaned.csv")

In [ ]:
df["Model"].value_counts().head(10)

Model
MODEL 3        25837
MODEL Y        23577
LEAF           13020
MODEL S         7473
BOLT EV         5419
VOLT            4881
MODEL X         4874
NIRO            2609
ID.4            2480
PRIUS PRIME     2473
Name: count, dtype: int64